on: [push]

jobs:
    mi-job:
        uses: OscarNeiraN/AAU1104-OscarNeira-Primary/.github/workflows/holamundo.yaml@main

        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
