on:
    push:
        tags:
        - 'v*.*.*'

jobs:
    deploy:
        uses: OscarNeiraN/AAU1104-OscarNeira-Primary/.github/workflows/deploy-api.yaml@main
        with:
            image-name: nueva-imagen-docker
            image-tag: ${{ github.ref_name }}
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # segundo-job:
    #     uses: OscarNeiraN/AAU1104-OscarNeira-Primary/.github/workflows/holamundo.yaml@main