on:
    push:
        tags:
        - 'v*.*.*' #tags de versionado

jobs:
    deploy:
        uses: maearaya221/primary/.github/workflows/deploy-api.yaml@main
        with:
            image-name: nueva-imagen-docker
            image-tag: ${{ github.ref_name }}
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
