on:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "v*.*.*"
   



jobs:
    deploy:
        uses: OscarNeiraN/AAU1104-OscarNeira-Primary/.github/workflows/test.yaml@main

